import os
from dotenv import load_dotenv

load_dotenv()

DIGITAL_UNITEC_API_URL = os.getenv("DIGITAL_UNITEC_API_URL")
DIGITAL_UNITEC_API_TOKEN = os.getenv("DIGITAL_UNITEC_API_TOKEN")

DIALER_UNITEC_API_URL = os.getenv("DIALER_UNITEC_API_URL")
DIALER_UNITEC_API_TOKEN = os.getenv("DIALER_UNITEC_API_TOKEN")

DIGITAL_UVM_API_URL = os.getenv("DIGITAL_UVM_API_URL")
DIGITAL_UVM_API_TOKEN = os.getenv("DIGITAL_UVM_API_TOKEN")

DIALER_UVM_API_URL = os.getenv("DIALER_UVM_API_URL")
DIALER_UVM_API_TOKEN = os.getenv("DIALER_UVM_API_TOKEN")